 version="1.0" encoding="UTF-8" ?>
<!--本地方式引入dtd约束-->
<!--<!DOCTYPE students SYSTEM "student.dtd">-->

<!--内部引入-->
<!DOCTYPE students[
		<!ELEMENT students (student*) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>
]>

<students>
	<student number="zaxxer_0001">
		<name>tom</name>
		<age>18</age>
		<sex>male</sex>
	</student>
	<student number="zaxxer_0006">
		<name>tom</name>
		<age>18</age>
		<sex>female</sex>
	</student>
</students>
